kafka:
  bootstrapServers: kafka-358735030-5-952533695.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-8-952533704.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-1-886374088.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-9-952533707.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-6-952533698.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-3-886374099.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-4-952533692.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-7-952533701.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092,kafka-358735030-2-886374094.prod-southcentralus-az.kafka-shared-non-prod.ms-df-messaging.prod-az-southcentralus-1.prod.us.walmart.net:9092
  autoCommitConfig: false
  maxPollRecords: 1
  maxPollIntervalMs: 300000
  heartbeatIntervalMs: 3000
  sessionTimeoutMs: 10000
  listenerConcurrency: 1
output:
  folderPath: /Users/g0k00kk/Desktop/Hermes/gdpData/STG-SCUS/25092020
input:
  searchPatternInMessage: hermes
logging:
  file:
    name: /Users/g0k00kk/Desktop/Hermes/gdpData/STG-SCUS/25092020/logs/gk-kafka-consumer.log
